# Generated by Django 5.0 on 2025-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_requestlog_city_requestlog_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('request_count', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
            },
        ),
    ]
